# Generated by Django 3.1.7 on 2021-05-10 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lmn', '0013_auto_20210505_1427'),
        ('lmn', '0015_auto_20210506_1213'),
    ]

    operations = [
    ]
