# Generated by Django 3.1.7 on 2021-05-11 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lmn', '0016_merge_20210510_1510'),
        ('lmn', '0017_auto_20210510_2009'),
    ]

    operations = [
    ]
